import { createHash } from 'node:crypto'
import {
    copyFileSync,
    existsSync,
    mkdirSync,
    readdirSync,
    readFileSync,
    renameSync,
    statSync,
    unlinkSync,
    writeFileSync,
} from 'node:fs'
import { homedir } from 'node:os'
import { join, relative } from 'node:path'
import { findMonorepoRoot, defaultHubPackageRoot } from './resolveUpgradeOffer'

export type ArtifactMeta = {
    version: string
    platform: string
    arch: string
    path: string
    sha256: string
    sizeBytes: number
    /** Hash of monorepo inputs that feed the compiled runner binary. */
    sourceFingerprint: string
}

const STUB_EMBEDDED_ASSETS = [
    '// This file is generated by hub fleet-upgrade artifact build (runner binary, no embedded web).',
    '// It intentionally contains no embedded assets.',
    '',
    'export interface EmbeddedWebAsset {',
    '    path: string;',
    '    sourcePath: string;',
    '    mimeType: string;',
    '}',
    '',
    'export const embeddedAssets: EmbeddedWebAsset[] = [];',
    '',
].join('\n')

function artifactsRoot(dataDir?: string): string {
    return join(dataDir ?? join(homedir(), '.hapi'), 'upgrade-artifacts')
}

/** Path-safe token: no `/`, `..`, whitespace, or other separators. */
const ARTIFACT_TOKEN_RE = /^[A-Za-z0-9._+-]+$/

export function artifactToken(name: string, value: string): string {
    if (!ARTIFACT_TOKEN_RE.test(value)) {
        throw new Error(`Invalid artifact ${name}`)
    }
    return value
}

export function artifactFileName(version: string, platform: string, arch: string): string {
    return `hapi-${artifactToken('version', version)}-${artifactToken('platform', platform)}-${artifactToken('arch', arch)}`
}

export function readArtifactMeta(
    version: string,
    platform: string,
    arch: string,
    dataDir?: string,
): ArtifactMeta | null {
    const dir = artifactsRoot(dataDir)
    const path = join(dir, artifactFileName(version, platform, arch))
    const metaPath = `${path}.json`
    if (!existsSync(path) || !existsSync(metaPath)) {
        return null
    }
    try {
        return JSON.parse(readFileSync(metaPath, 'utf8')) as ArtifactMeta
    } catch {
        return null
    }
}

function writeMeta(meta: ArtifactMeta): void {
    writeFileSync(`${meta.path}.json`, JSON.stringify(meta, null, 2))
}

function listFilesRecursive(root: string): string[] {
    const out: string[] = []
    const walk = (dir: string): void => {
        let entries
        try {
            entries = readdirSync(dir, { withFileTypes: true })
        } catch {
            return
        }
        for (const entry of entries) {
            if (entry.name === 'node_modules' || entry.name === 'dist' || entry.name === '.git') {
                continue
            }
            const full = join(dir, entry.name)
            if (entry.isDirectory()) {
                walk(full)
            } else if (entry.isFile()) {
                out.push(full)
            }
        }
    }
    if (existsSync(root)) {
        walk(root)
    }
    return out
}

/**
 * Fingerprint the sources that feed hub-artifact compiles.
 * Version alone is not enough: soup hubs often keep one package version across
 * many commits; a cache keyed only by version would keep serving a stale binary.
 *
 * Scope matches what `bun build --compile cli/src/bootstrap.ts` actually pulls:
 * CLI + shared + hub (command registry / startHub) + embedded tool assets.
 *
 * Content-addressed (not size+mtime): clean checkouts and pinned-tool re-downloads
 * change mtime with identical bytes and must not flap `targetGeneration`.
 * Skip `hub/src/web/embeddedAssets.generated.ts` — compile stubs it out via
 * `withStubEmbeddedAssets`, so web-only regenerations must not force a fleet upgrade.
 * Skip downloaded `shared/tools/tunwg/tunwg-*` caches — pin changes live in
 * `hub/src/upgrade/tunwgPin.ts`; hashing platform caches flaps generation across
 * a mixed-platform fleet.
 */
export function fingerprintArtifactInputs(monorepoRoot: string): string {
    const hash = createHash('sha256')
    for (const file of listArtifactInputFiles(monorepoRoot)) {
        const rel = relative(monorepoRoot, file).split('\\').join('/')
        hash.update(rel)
        hash.update('\0')
        hash.update(readFileSync(file))
        hash.update('\0')
    }
    return hash.digest('hex')
}

/**
 * Cheap signature (path + size + mtime) for deciding whether the content
 * fingerprint needs recomputation. Used so the 30s offer/heartbeat path does
 * not re-read ~95MB of tool archives on every TTL miss when nothing changed.
 */
export function fingerprintArtifactInputStats(monorepoRoot: string): string {
    const hash = createHash('sha256')
    for (const file of listArtifactInputFiles(monorepoRoot)) {
        const rel = relative(monorepoRoot, file).split('\\').join('/')
        const st = statSync(file)
        hash.update(rel)
        hash.update('\0')
        hash.update(`stat:${st.size}:${Math.trunc(st.mtimeMs)}`)
        hash.update('\0')
    }
    return hash.digest('hex')
}

let cachedContentFingerprint: { signature: string; value: string } | null = null

/** Content fingerprint with a stats-signature gate for hot offer resolution. */
export function resolveArtifactSourceFingerprint(monorepoRoot: string): string {
    const signature = fingerprintArtifactInputStats(monorepoRoot)
    if (cachedContentFingerprint && cachedContentFingerprint.signature === signature) {
        return cachedContentFingerprint.value
    }
    const value = fingerprintArtifactInputs(monorepoRoot)
    cachedContentFingerprint = { signature, value }
    return value
}

/** Test helper — drop the in-process content-fingerprint cache. */
export function __resetArtifactFingerprintCacheForTests(): void {
    cachedContentFingerprint = null
}

function listArtifactInputFiles(monorepoRoot: string): string[] {
    const treeRoots = [
        join(monorepoRoot, 'cli', 'src'),
        join(monorepoRoot, 'hub', 'src'),
        join(monorepoRoot, 'shared', 'src'),
        join(monorepoRoot, 'cli', 'tools'),
        join(monorepoRoot, 'shared', 'tools'),
    ]
    const singles = [
        join(monorepoRoot, 'cli', 'package.json'),
        join(monorepoRoot, 'hub', 'package.json'),
        join(monorepoRoot, 'shared', 'package.json'),
        join(monorepoRoot, 'package.json'),
        join(monorepoRoot, 'bun.lock'),
    ]
    const files = [
        ...treeRoots.flatMap(listFilesRecursive),
        ...singles.filter((path) => existsSync(path)),
    ]
    return [...new Set(files)].sort().filter((file) => {
        const rel = relative(monorepoRoot, file).split('\\').join('/')
        if (
            rel === 'hub/src/web/embeddedAssets.generated.ts'
            || /^hub\/src\/web\/embeddedAssets\.generated\.ts\.fleet-upgrade\..+\.bak$/.test(rel)
        ) {
            return false
        }
        // Platform-specific downloaded tunwg binaries — pin is in hub source.
        if (rel.startsWith('shared/tools/tunwg/tunwg-')) {
            return false
        }
        return true
    })
}

export function isArtifactCacheFresh(
    meta: ArtifactMeta | null,
    sourceFingerprint: string,
): boolean {
    if (!meta || !existsSync(meta.path)) {
        return false
    }
    // Pre-fingerprint metas (and empty fingerprints) are never reusable —
    // same package version can hide newer source.
    return typeof meta.sourceFingerprint === 'string'
        && meta.sourceFingerprint.length > 0
        && meta.sourceFingerprint === sourceFingerprint
}

function featureFlagFor(platform: string, arch: string): string {
    const platformToken = platform === 'win32' ? 'WIN32' : platform.toUpperCase()
    return `HAPI_TARGET_${platformToken}_${arch.toUpperCase()}`
}

/**
 * Map Node's process.platform/arch to a Bun `--compile --target=` string.
 * Bun cross-compiles these from any host (Linux→Windows is the common
 * fleet-upgrade case: hub on oos-linux, runners on Teemo/OOS-VR2).
 */
export function bunCompileTarget(platform: string, arch: string): string {
    if (platform === 'linux' && arch === 'x64') {
        return 'bun-linux-x64-baseline'
    }
    if (platform === 'linux' && arch === 'arm64') {
        return 'bun-linux-arm64'
    }
    if (platform === 'win32' && arch === 'x64') {
        // HAPI only publishes/ships @twsxtd/hapi-win32-x64. Bun can compile
        // bun-windows-arm64, but fleet-upgrade must match the supported binary matrix.
        return 'bun-windows-x64'
    }
    if (platform === 'darwin' && (arch === 'x64' || arch === 'arm64')) {
        return `bun-darwin-${arch}`
    }
    throw new Error(`Unsupported compile target: ${platform}/${arch}`)
}

/**
 * Bun auto-appends `.exe` for Windows targets when the outfile has no
 * extension. Prefer an explicit `.exe` outfile, then normalize back to the
 * extensionless artifact path we serve (download bytes don't care about
 * the hub-side filename; Windows runners rename on install).
 *
 * Same-version rebuilds: always prefer a freshly compiled `.exe` over a
 * stale extensionless `outPath` left from a previous build — otherwise the
 * hub hashes OLD bytes under the NEW sourceFingerprint and silently ships
 * the previous generation to Windows runners.
 */
export function normalizeCompiledArtifactPath(outPath: string, platform: string): string {
    if (platform !== 'win32') {
        return outPath
    }
    const withExe = `${outPath}.exe`
    if (existsSync(withExe)) {
        try {
            if (existsSync(outPath)) {
                unlinkSync(outPath)
            }
        } catch {
            // best-effort; rename may still replace on Unix-like FS layers
        }
        renameSync(withExe, outPath)
        return outPath
    }
    return outPath
}

function tunwgBinaryPath(monorepoRoot: string, platform: string, arch: string): string {
    const name = platform === 'win32'
        ? `tunwg-${arch}-win32.exe`
        : `tunwg-${arch}-${platform === 'darwin' ? 'darwin' : 'linux'}`
    // win32 uses x64 only in practice
    const file = platform === 'win32' ? 'tunwg-x64-win32.exe' : name
    return join(monorepoRoot, 'shared', 'tools', 'tunwg', file)
}

async function ensureTunwgBinary(
    monorepoRoot: string,
    platform: string,
    arch: string,
): Promise<void> {
    const { ensurePinnedTunwgForCompile } = await import('./tunwgPin')
    await ensurePinnedTunwgForCompile(monorepoRoot, platform, arch)
    const path = tunwgBinaryPath(monorepoRoot, platform, arch)
    if (!existsSync(path)) {
        throw new Error(`Pinned tunwg binary missing after download: ${path}`)
    }
}

function requiredToolArchives(cliRoot: string, platform: string, arch: string): string[] {
    let platformDir: string
    if (platform === 'darwin') {
        platformDir = arch === 'arm64' ? 'arm64-darwin' : 'x64-darwin'
    } else if (platform === 'linux') {
        platformDir = arch === 'arm64' ? 'arm64-linux' : 'x64-linux'
    } else if (platform === 'win32') {
        platformDir = 'x64-win32'
    } else {
        throw new Error(`Unsupported platform: ${platform}`)
    }
    return [
        join(cliRoot, 'tools', 'archives', `difftastic-${platformDir}.tar.gz`),
        join(cliRoot, 'tools', 'archives', `ripgrep-${platformDir}.tar.gz`),
    ]
}

/**
 * Write empty embedded-web manifest so bun --compile does not pull stale
 * hashed web/dist imports from a previous generate:embedded-web-assets run.
 * Restores the previous file in finally.
 *
 * On restore failure: keep the `.bak` so a Windows rename/copy glitch cannot
 * destroy the only original copy and leave the empty stub in the live tree.
 */
export function withStubEmbeddedAssets<T>(
    monorepoRoot: string,
    run: () => Promise<T>,
    deps: {
        /** Test seam: override how the backup is written back onto the manifest. */
        restoreFromBackup?: (backupPath: string, manifestPath: string) => void
    } = {},
): Promise<T> {
    const manifestPath = join(monorepoRoot, 'hub', 'src', 'web', 'embeddedAssets.generated.ts')
    // Unique backup per call so overlapping builds cannot clobber each other's restore.
    const backupPath = `${manifestPath}.fleet-upgrade.${process.pid}.${Date.now()}.${Math.random().toString(16).slice(2)}.bak`
    const hadOriginal = existsSync(manifestPath)
    if (hadOriginal) {
        copyFileSync(manifestPath, backupPath)
    }
    writeFileSync(manifestPath, STUB_EMBEDDED_ASSETS, 'utf8')

    const restore = (): void => {
        // No original → nothing to restore; treat as success so any stray bak is cleaned.
        let restored = !hadOriginal
        try {
            if (hadOriginal && existsSync(backupPath)) {
                // copy (not rename) so a failed overwrite still leaves the backup intact.
                const restoreFn = deps.restoreFromBackup
                    ?? ((from: string, to: string) => {
                        copyFileSync(from, to)
                    })
                restoreFn(backupPath, manifestPath)
                restored = true
            } else if (!hadOriginal && existsSync(manifestPath)) {
                unlinkSync(manifestPath)
                restored = true
            }
        } catch (error) {
            // Keep .bak; fail the build so we never hash/serve artifacts while the
            // live tree still holds the empty stub (and so the stub is not treated
            // as the next "original").
            throw new Error(
                `Failed to restore embedded asset manifest; backup kept at ${backupPath}`,
                { cause: error },
            )
        }
        if (restored) {
            try {
                if (existsSync(backupPath)) {
                    unlinkSync(backupPath)
                }
            } catch {
                // ignore
            }
        }
    }

    return run().finally(restore)
}

/** Serialize artifact compiles — concurrent heartbeats must not race the stub/restore. */
let artifactBuildLock: Promise<void> = Promise.resolve()

async function withArtifactBuildLock<T>(run: () => Promise<T>): Promise<T> {
    const previous = artifactBuildLock
    let release!: () => void
    artifactBuildLock = new Promise<void>((resolve) => {
        release = resolve
    })
    await previous
    try {
        return await run()
    } finally {
        release()
    }
}

/**
 * Ensure a compiled CLI artifact exists for platform/arch.
 * Uses the same bootstrap entry as `cli/scripts/build-executable.ts` (without
 * embedded web assets) so remotes get a runnable runner binary.
 */
export async function ensureCliArtifact(options: {
    version: string
    platform: string
    arch: string
    dataDir?: string
    hubPackageRoot?: string
    bunCommand?: string
}): Promise<ArtifactMeta> {
    const hubRoot = options.hubPackageRoot ?? defaultHubPackageRoot()
    const monorepo = findMonorepoRoot(hubRoot)
    if (!monorepo) {
        throw new Error('No monorepo root found; cannot build hub-artifact')
    }

    return await withArtifactBuildLock(async () => {
        // Resolve (and validate) the Bun target up front — throws for
        // unsupported platform/arch. Same-host used to be required; Bun now
        // cross-compiles win32/darwin/linux from any host.
        const target = bunCompileTarget(options.platform, options.arch)

        const bun = options.bunCommand
            ?? (process.execPath.includes('bun') ? process.execPath : 'bun')
        // Download/verify pinned tunwg BEFORE fingerprinting so a clean tree
        // does not cache a pre-download fingerprint and force a second compile.
        await ensureTunwgBinary(monorepo, options.platform, options.arch)

        const sourceFingerprint = resolveArtifactSourceFingerprint(monorepo)
        const cached = readArtifactMeta(options.version, options.platform, options.arch, options.dataDir)
        if (isArtifactCacheFresh(cached, sourceFingerprint)) {
            return cached!
        }

        const cliRoot = join(monorepo, 'cli')
        const entry = join(cliRoot, 'src', 'bootstrap.ts')
        if (!existsSync(entry)) {
            throw new Error(`CLI bootstrap missing: ${entry}`)
        }

        for (const archive of requiredToolArchives(cliRoot, options.platform, options.arch)) {
            if (!existsSync(archive)) {
                throw new Error(`Missing tool archive for compile: ${archive}`)
            }
        }

        const dir = artifactsRoot(options.dataDir)
        mkdirSync(dir, { recursive: true })
        const outPath = join(dir, artifactFileName(options.version, options.platform, options.arch))
        // Explicit .exe so Bun doesn't surprise us with an auto-suffix we then miss.
        const compileOut = options.platform === 'win32' ? `${outPath}.exe` : outPath
        // Drop stale win32 outputs before compile so a same-version rebuild cannot
        // leave normalize choosing yesterday's extensionless bytes over a fresh .exe.
        if (options.platform === 'win32') {
            for (const stale of [outPath, compileOut]) {
                try {
                    if (existsSync(stale)) {
                        unlinkSync(stale)
                    }
                } catch {
                    // best-effort; normalize still prefers .exe when both exist
                }
            }
        }
        const feature = featureFlagFor(options.platform, options.arch)

        await withStubEmbeddedAssets(monorepo, async () => {
            const proc = Bun.spawn([
                bun,
                'build',
                '--compile',
                '--no-compile-autoload-dotenv',
                `--feature=${feature}`,
                `--target=${target}`,
                `--outfile=${compileOut}`,
                entry,
            ], {
                cwd: cliRoot,
                stdout: 'pipe',
                stderr: 'pipe',
                env: process.env,
            })
            const [stdout, stderr, code] = await Promise.all([
                new Response(proc.stdout).text(),
                new Response(proc.stderr).text(),
                proc.exited,
            ])
            const produced = normalizeCompiledArtifactPath(outPath, options.platform)
            if (code !== 0 || !existsSync(produced)) {
                throw new Error(`bun compile failed: ${stderr || stdout}`)
            }
        })

        const buf = readFileSync(outPath)
        const sha256 = createHash('sha256').update(buf).digest('hex')
        const meta: ArtifactMeta = {
            version: options.version,
            platform: options.platform,
            arch: options.arch,
            path: outPath,
            sha256,
            sizeBytes: statSync(outPath).size,
            sourceFingerprint,
        }
        writeMeta(meta)
        return meta
    })
}
